# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(285, 217)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.bobberColorLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bobberColorLabel.sizePolicy().hasHeightForWidth())
        self.bobberColorLabel.setSizePolicy(sizePolicy)
        self.bobberColorLabel.setMinimumSize(QtCore.QSize(20, 20))
        self.bobberColorLabel.setMaximumSize(QtCore.QSize(20, 20))
        self.bobberColorLabel.setText("")
        self.bobberColorLabel.setObjectName("bobberColorLabel")
        self.horizontalLayout_3.addWidget(self.bobberColorLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.hexColorLabel = QtWidgets.QLabel(self.centralwidget)
        self.hexColorLabel.setText("")
        self.hexColorLabel.setObjectName("hexColorLabel")
        self.horizontalLayout_3.addWidget(self.hexColorLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.thresholdBobberSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdBobberSpinBox.sizePolicy().hasHeightForWidth())
        self.thresholdBobberSpinBox.setSizePolicy(sizePolicy)
        self.thresholdBobberSpinBox.setMinimumSize(QtCore.QSize(40, 0))
        self.thresholdBobberSpinBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.thresholdBobberSpinBox.setObjectName("thresholdBobberSpinBox")
        self.verticalLayout_2.addWidget(self.thresholdBobberSpinBox)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.thresholdCatchSpinBox = QtWidgets.QSpinBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.thresholdCatchSpinBox.sizePolicy().hasHeightForWidth())
        self.thresholdCatchSpinBox.setSizePolicy(sizePolicy)
        self.thresholdCatchSpinBox.setMinimumSize(QtCore.QSize(40, 0))
        self.thresholdCatchSpinBox.setMaximumSize(QtCore.QSize(40, 16777215))
        self.thresholdCatchSpinBox.setObjectName("thresholdCatchSpinBox")
        self.verticalLayout_2.addWidget(self.thresholdCatchSpinBox)
        self.jumpToBobberCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.jumpToBobberCheck.setObjectName("jumpToBobberCheck")
        self.verticalLayout_2.addWidget(self.jumpToBobberCheck)
        self.verboseCheck = QtWidgets.QCheckBox(self.centralwidget)
        self.verboseCheck.setObjectName("verboseCheck")
        self.verticalLayout_2.addWidget(self.verboseCheck)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(350, 0, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout.addWidget(self.startButton)
        self.areaButton = QtWidgets.QPushButton(self.centralwidget)
        self.areaButton.setObjectName("areaButton")
        self.verticalLayout.addWidget(self.areaButton)
        self.colorButton = QtWidgets.QPushButton(self.centralwidget)
        self.colorButton.setObjectName("colorButton")
        self.verticalLayout.addWidget(self.colorButton)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GetTheFish"))
        self.label_5.setText(_translate("MainWindow", "Bobber Color"))
        self.label.setText(_translate("MainWindow", "Threshold Bobber"))
        self.label_2.setText(_translate("MainWindow", "Threshold Catch"))
        self.jumpToBobberCheck.setText(_translate("MainWindow", "Jump to Bobber"))
        self.verboseCheck.setText(_translate("MainWindow", "verbose"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.areaButton.setText(_translate("MainWindow", "Set Area"))
        self.colorButton.setText(_translate("MainWindow", "Select Color"))

